FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime

RUN apt update -y && apt install -y git

# Non-root user
RUN useradd -m -s /bin/bash -G sudo -u 1000 cvl
USER cvl

RUN pip install torchvision==0.19.1 numpy==2.1.2 scipy==1.14.1 \
    clean-fid==0.1.35 wandb==0.18.3 timm==1.0.9 datasets==3.0.2
# torchdyn for neural ODEs, and POT for optimal transport
RUN pip install transformers==4.47.1
RUN pip install diffusers accelerate einops tqdm
RUN pip install git+https://github.com/openai/CLIP.git
RUN pip install h5py img2dataset webdataset

